# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9526cd074ce3d38472afc0e9d8b7f90f9e8cc458f65fd2e237038b0ec99ae69e6dd1635160869a7a5563fe0ed319b52294c03f3dbdedcccea3c2121d7bb67296

test:
  secret_key_base: a32ad39032ffbd12d53892b189d67a5444f88fa63dfb3888cb909bf904e3014891d4c62b6537042074c4dc5eb8da722441d527cadb14aa1ecc105961dccdb627

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
